#!/usr/bin/env python3
"""Validate TEP metadata and keep the index in README.md in sync.

Usage:
    scripts/validate-teps.py               check all TEPs and the index
    scripts/validate-teps.py --write-index regenerate the index, then check

Requires PyYAML.
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TEPS_DIR = ROOT / "teps"
README = ROOT / "README.md"

DIR_PATTERN = re.compile(r"^(\d{4})-[a-z0-9]+(-[a-z0-9]+)*$")
HANDLE_PATTERN = re.compile(r"^@[A-Za-z0-9-]+(/[A-Za-z0-9_.-]+)?$")
INDEX_BEGIN = "<!-- BEGIN TEP INDEX: generated by scripts/validate-teps.py --write-index -->"
INDEX_END = "<!-- END TEP INDEX -->"

STATUSES = {
    "draft",
    "provisional",
    "implementable",
    "implemented",
    "deferred",
    "rejected",
    "withdrawn",
    "replaced",
}
REQUIRED = [
    "tep",
    "title",
    "status",
    "authors",
    "approvers",
    "tracking-issue",
    "created",
    "last-updated",
]


def read_front_matter(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("missing YAML front matter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise ValueError("unterminated YAML front matter")
    # BaseLoader keeps every value a string, so "0001" is not read as the int 1.
    meta = yaml.load(text[4:end], Loader=yaml.BaseLoader)
    if not isinstance(meta, dict):
        raise ValueError("front matter is not a mapping")
    return meta


def check_tep(directory, meta):
    errors = []
    number = DIR_PATTERN.match(directory.name).group(1)

    for field in REQUIRED:
        if field not in meta:
            errors.append(f"missing field '{field}'")

    if meta.get("tep") != number:
        errors.append(f"'tep: {meta.get('tep')}' does not match directory number {number}")
    if meta.get("status") not in STATUSES:
        errors.append(f"unknown status '{meta.get('status')}'")

    for field in ("authors", "approvers"):
        handles = meta.get(field)
        if not isinstance(handles, list) or not handles:
            errors.append(f"'{field}' must be a non-empty list")
            continue
        for handle in handles:
            if not HANDLE_PATTERN.match(handle):
                errors.append(f"'{field}' entry '{handle}' is not a GitHub handle like @name")

    for field in ("created", "last-updated"):
        try:
            datetime.date.fromisoformat(meta.get(field, ""))
        except ValueError:
            errors.append(f"'{field}' must be a YYYY-MM-DD date")

    issue = meta.get("tracking-issue")
    if issue not in (None, "null", "") and not issue.startswith("https://github.com/"):
        errors.append("'tracking-issue' must be a GitHub URL or null")

    for field in ("replaces", "superseded-by"):
        refs = meta.get(field, [])
        if not isinstance(refs, list) or not all(re.fullmatch(r"\d{4}", r) for r in refs):
            errors.append(f"'{field}' must be a list of four-digit TEP numbers")
    if meta.get("status") == "replaced" and not meta.get("superseded-by"):
        errors.append("status 'replaced' requires 'superseded-by'")

    return errors


def render_index(teps):
    lines = [
        INDEX_BEGIN,
        "| TEP | Title | Status | Authors |",
        "|---|---|---|---|",
    ]
    for number, directory, meta in teps:
        link = f"teps/{directory.name}/README.md"
        authors = ", ".join(meta["authors"])
        lines.append(f"| [{number}]({link}) | {meta['title']} | {meta['status']} | {authors} |")
    lines.append(INDEX_END)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write-index", action="store_true", help="regenerate the index in README.md")
    args = parser.parse_args()

    errors = []
    teps = []
    seen = {}

    for directory in sorted(p for p in TEPS_DIR.iterdir() if p.is_dir()):
        rel = directory.relative_to(ROOT)
        match = DIR_PATTERN.match(directory.name)
        if not match:
            errors.append(f"{rel}: directory name must look like NNNN-short-title")
            continue
        number = match.group(1)
        if number in seen:
            errors.append(f"{rel}: TEP number {number} is already used by {seen[number]}")
        seen[number] = rel

        readme = directory / "README.md"
        if not readme.is_file():
            errors.append(f"{rel}: missing README.md")
            continue
        try:
            meta = read_front_matter(readme)
        except (ValueError, yaml.YAMLError) as err:
            errors.append(f"{rel}/README.md: {err}")
            continue

        errors.extend(f"{rel}/README.md: {e}" for e in check_tep(directory, meta))
        if number != "0000":
            teps.append((number, directory, meta))

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    readme_text = README.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(INDEX_BEGIN) + r".*?" + re.escape(INDEX_END), re.DOTALL)
    if not pattern.search(readme_text):
        print("error: README.md is missing the TEP index markers", file=sys.stderr)
        return 1
    expected = pattern.sub(lambda _: render_index(teps), readme_text)

    if args.write_index:
        README.write_text(expected, encoding="utf-8")
    elif expected != readme_text:
        print("error: the index in README.md is out of date; run scripts/validate-teps.py --write-index", file=sys.stderr)
        return 1

    print(f"ok: {len(teps)} TEP(s) validated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
